<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SW.Bitween.PgSql</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.19">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\SW.Bitween.Api\SW.Bitween.Api.csproj" />
    <PackageReference Include="SimplyWorks.Scheduler.PgSql" Version="8.1.7" />
  </ItemGroup>


  <ItemGroup>
    <Compile Remove="Migrations\20260212153331_ApiGateway.cs" />
    <Compile Remove="Migrations\20260212153331_ApiGateway.Designer.cs" />
  </ItemGroup>

</Project>
