<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SW.Bitween.PgSql</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="EFCore.NamingConventions" Version="8.0.3" />

  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\SW.Bitween.Api\SW.Bitween.Api.csproj" />
  </ItemGroup>

</Project>
